API_PREFIX = "/reports"
DEFAULT_EXPORT_LIMIT = 1000
MAX_EXPORT_LIMIT = 5000
MAX_DATE_RANGE_DAYS = 366
CONFIRMED_CHALLAN_STATUS = "CONFIRMED"
DATE_RANGE_ERROR = "Date range must be valid and at most 366 days"
CSV_FILENAME = "attachment; filename=challans.csv"
ALLOWED_ROLES = ("ADMIN", "SALES", "WAREHOUSE", "ACCOUNTS")
READ_ONLY_SESSION_SQL = "SET SESSION TRANSACTION READ ONLY"
HTTP_UNAUTHORIZED = 401
HTTP_UNPROCESSABLE_ENTITY = 422
HTTP_SERVICE_UNAVAILABLE = 503
AUTH_REQUIRED_MESSAGE = "Authentication required"
AUTH_INVALID_MESSAGE = "Invalid or expired token"
DATABASE_UNAVAILABLE_MESSAGE = "Reporting database unavailable"
